seed: 42

data:
  aptos_dir: ./data/aptos
  messidor_dir: ./data/messidor
  image_size: 224
  batch_size: 8
  num_workers: 2

training:
  lr: 0.0001
  weight_decay: 0.00001
  focal_gamma: 2.0
  alpha_iqa: 0.5
  early_stop_patience: 5
  max_epochs: 10
  gpus: 0
  devices: 1
  precision: 32
  accumulate_grad_batches: 1


logging:
  model_ckpt: ./checkpoints/best.ckpt




